"""Backend protocol — structural typing contract for agent backends."""

from typing import AsyncIterator, Optional, Protocol, runtime_checkable

from app.events import AgentEvent


@runtime_checkable
class BackendLike(Protocol):
    @property
    def session_id(self) -> Optional[str]: ...
    async def connect(self) -> None: ...
    async def send(self, message: str) -> None: ...
    async def events(self) -> AsyncIterator[AgentEvent]: ...
    async def interrupt(self) -> bool | None: ...
    async def disconnect(self) -> None: ...
