"""Backend protocol — structural typing contract for agent backends."""

from typing import AsyncIterator, Optional, Protocol

from app.events import AgentEvent


class BackendLike(Protocol):
    @property
    def session_id(self) -> Optional[str]: ...
    async def connect(self) -> None: ...
    async def send(self, message: str) -> None: ...
    async def events(self) -> AsyncIterator[AgentEvent]: ...
    async def interrupt(self) -> None: ...
    async def disconnect(self) -> None: ...
